name: Diduknow
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64221
title: 'Drugs, Addiction and Recovery'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e3e4e6'
    - '#5799f7'
    - '#c0c4c5'
    - '#707477'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
