layout_spectrum: 0.8375601
typography_spectrum: 0.0847185
color:
  saturation: 0.3634227
  lightness: 0.8536859
  brandStrength: 0.8726999
  rhythmicContrast: 0.8080712
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Diduknow
